version: "3"

includes:
  lint: "lint-tasks.yml"
  utils: "tools/yscope-dev-utils/taskfiles/utils.yml"

tasks:
  default:
    deps: ["lint"]

  clean:
    cmds: ["rm -rf '{{.G_BUILD_DIR}}' '{{.G_LINT_VENV_DIR}}'"]

  init:
    internal: true
    silent: true
    run: "once"
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"
