name: "Build"

on:
  pull_request:
    paths:
      - ".github/workflows/build.yaml"
      - "CMakeLists.txt"
      - "examples/**/*"
      - "src/**/*"
  push:
    paths:
      - ".github/workflows/build.yaml"
      - "CMakeLists.txt"
      - "examples/**/*"
      - "src/**/*"
  workflow_call:

# Concurrency group to prevent multiple workflow instances from trying to publish releases
concurrency: "${{github.workflow}}-${{github.ref}}"

jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        build_type: ["Release", "Debug"]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: "actions/checkout@v4"

      - run: "cmake -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}"

      - run: "cmake --build ./build --config ${{ matrix.build_type }}"

      - run: "cmake --install ./build --prefix ./install"

      - run: "cmake -S examples -B ./examples/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}"

      - run: "cmake --build ./examples/build --config ${{ matrix.build_type }}"
