name: "doxygen"

on:
  pull_request:
  push:
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  build:
    name: "Build Doxygen Docs"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          lfs: "true"
          submodules: "recursive"

      - name: "Install task"
        shell: "bash"
        run: "npm install -g @go-task/cli"

      - name: "Build doxygen docs"
        shell: "bash"
        run: "task doxygen:site"

      # Upload the built docs site if we need to debug any issues
      - if: >-
          contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name)
          && ('refs/heads/main' == github.ref || startsWith(github.ref, 'refs/tags/v'))
        uses: "actions/upload-artifact@v4"
        with:
          name: "doxygen-html"
          path: "build/docs/html"
          if-no-files-found: "error"

          # Retain the artifact for a week
          retention-days: 7
